[package]
name = "pls"
version = "0.1.0"
edition = "2021"


[dependencies]
egui_glow = { version = "0.15", default-features = false, features = ["default_fonts", "links"] }
# NOTE: Using a wildcard import to have the same version as what's used by egui_glow:
glow = "*"
glutin = "*"
egui = "*"
