[package]
name = "pls"
version = "0.1.0"
authors = ["Tomas Sedovic <tomas@sedovic.cz>"]
edition = "2021"
exclude = ["/test/**", "/venv/**", "/bin/**"]


[dependencies]
anyhow = "1.0"
directories = "4.0"
# TODO: switch to upstream once this PR is merged:
# https://github.com/emilk/egui/pull/1031
eframe = { git = "https://github.com/tomassedovic/emilk-egui.git", branch = "eframe-optional-deps", default-features = false, features = ["egui_glow"] }
toml_edit = "0.10"
opener = "0.5"
hostname = "0.3"
humanesort = "0.1.0-alpha"

[features]
default = ["test"]
test = []
