[package]
name = "pls"
version = "0.1.0"
authors = ["Tomas Sedovic <tomas@sedovic.cz>"]
edition = "2021"
exclude = ["/test/**", "/venv/**", "/bin/**"]


[dependencies]
anyhow = "1.0"
directories = "4.0"
# TODO: bundle egui for now and open an issue?
# The issue is that the default egui dependency (egui_glow's default dependencies require OS deps for clipboard etc.)
eframe = { path = "../../3pc/src/github.com/emilk/egui/eframe/", default-features = false, features = ["egui_glow", "default_fonts"] }
toml_edit = "0.10"
opener = "0.5"
hostname = "0.3"
humanesort = "0.1.0-alpha"

[features]
default = ["test"]
test = []
