name: Build and Test pls

on:
  push:
    branches: [ master ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
        - os: ubuntu-latest
          target_triple: x86_64-unknown-linux-gnu
          archive_ext: tar.gz
          cargo_bundle: false
          extra_features: linux-extra-features
          build_time_dependencies: ""
          exe_extension: ""
        - os: windows-latest
          target_triple: x86_64-pc-windows-msvc
          archive_ext: zip
          cargo_bundle: false
          extra_features: windows-extra-features
          build_time_dependencies: ""
          exe_extension: "exe"
        - os: macos-latest
          target_triple: x86_64-apple-darwin
          cargo_bundle: true
          archive_ext: zip
          extra_features: macos-extra-features
          build_time_dependencies: ""
          exe_extension: ""
    runs-on: ${{ matrix.platform.os }}

    env:
      EXECUTABLE_EXTENSION: ${{ matrix.platform.exe_extension }}
      TARGET_TRIPLE: ${{ matrix.platform.target_triple }}
      ARCHIVE_EXT: ${{ matrix.platform.archive_ext }}
      CARGO_BUNDLE: ${{ matrix.platform.cargo_bundle }}
      VERSION: ${{ github.ref_name }}
    steps:
    - uses: actions/checkout@v2
    - name: Check for warnings
      run: cargo clippy
      env:
        RUSTFLAGS: -D warnings
    - name: Build the release
      run: >
        cargo build --verbose --release --no-default-features
        --features "${{ matrix.platform.extra_features }}"
    - name: Install cargo bundle
      run: cargo install cargo-bundle
      if: ${{ matrix.platform.cargo_bundle }}
    - name: Create the release bundle
      run: >
        cargo bundle --no-default-features --release
        --features "${{ matrix.platform.extra_features }}"
      if: ${{ matrix.platform.cargo_bundle }}
    - name: Package the release
      run: cargo run --bin deploy --release
    - name: Upload to the Release page
      uses: softprops/action-gh-release@v1
      with:
        files: |
          pls-${{ github.ref_name }}-${{ matrix.platform.target_triple }}.${{ matrix.platform.archive_ext }}
      if: ${{ github.ref_type == 'tag' }}
