name: Build and Test pls

on:
  push:
    branches: [ master ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
        - os: ubuntu-latest
          target_triple: x86_64-unknown-linux-gnu
          archive_ext: tar.gz
          extra_features: linux-extra-features
          build_time_dependencies: ""
          exe_extension: ""
        - os: windows-latest
          target_triple: x86_64-pc-windows-msvc
          archive_ext: zip
          extra_features: windows-extra-features
          build_time_dependencies: ""
          exe_extension: ".exe"
        - os: macos-latest
          target_triple: x86_64-apple-darwin
          archive_ext: zip
          extra_features: macos-extra-features
          build_time_dependencies: ""
          exe_extension: ""
    runs-on: ${{ matrix.platform.os }}

    env:
      # NOTE: not needed now, but it might simplify the deploy script
      TARGET_TRIPLE: ${{ matrix.platform.target_triple }}
      ARCHIVE_EXT: ${{ matrix.platform.archive_ext }}
    steps:
    - uses: actions/checkout@v2
    - name: Check for warnings
      run: cargo clippy
      env:
        RUSTFLAGS: -D warnings
    - name: Build the release
      run: >
        cargo build --verbose --release --no-default-features
        --features "${{ matrix.platform.extra_features }}"
    - name: Prepare the release build
      # TODO: zip it up with readme and license?
      run: cargo run --bin deploy
    - name: Upload to the Release page
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/release/pls-${{ matrix.platform.target_triple }}${{ matrix.platform.exe_extension }}
      if: startsWith(github.ref, 'refs/tags/')
